-- ============================================================
-- Migración: categorías de productos + tabla de componentes de promo
-- Ejecutar en Supabase → SQL Editor
-- ============================================================

-- 1) Columna de categoría en products (idempotente)
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS category text DEFAULT '';

-- 1b) Columna de presentación en products (idempotente)
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS presentation text DEFAULT '';

-- 2) Tabla de categorías (opcional, para catálogo centralizado)
CREATE TABLE IF NOT EXISTS public.categories (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billar_id text NOT NULL DEFAULT 'BILLAR_001',
  name      text NOT NULL,
  CONSTRAINT categories_name_unique UNIQUE (name)
);

-- 3) Tabla de componentes de promo (qué productos arma cada promo)
CREATE TABLE IF NOT EXISTS public.promo_items (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id bigint NOT NULL,   -- id del producto promo (is_promo = 1)
  child_id  bigint NOT NULL,   -- id del producto incluido
  quantity  integer NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS promo_items_parent_idx ON public.promo_items (parent_id);

-- ============================================================
-- RLS (Row Level Security) para las tablas nuevas
-- ============================================================
ALTER TABLE public.categories  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promo_items ENABLE ROW LEVEL SECURITY;

-- Políticas categories
DROP POLICY IF EXISTS "categories_all" ON public.categories;
CREATE POLICY "categories_all"
  ON public.categories FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Políticas promo_items
DROP POLICY IF EXISTS "promo_items_all" ON public.promo_items;
CREATE POLICY "promo_items_all"
  ON public.promo_items FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');
