-- ============================================================
-- Migración: catálogo de CONCEPTOS de retiro/gasto de caja
-- Ejecutar en Supabase → SQL Editor
-- ============================================================

-- 1) Tabla de conceptos de retiro/gasto
CREATE TABLE IF NOT EXISTS public.cash_outflow_concepts (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billar_id text NOT NULL DEFAULT 'BILLAR_001',
  name      text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cash_outflow_concepts_billar_name_unique UNIQUE (billar_id, name)
);

-- Índice por billar para consultas rápidas
CREATE INDEX IF NOT EXISTS cash_outflow_concepts_billar_idx
  ON public.cash_outflow_concepts (billar_id);

-- ============================================================
-- RLS (Row Level Security)
-- ============================================================
ALTER TABLE public.cash_outflow_concepts ENABLE ROW LEVEL SECURITY;

-- Política de lectura/escritura para usuarios autenticados
DROP POLICY IF EXISTS "cash_outflow_concepts_all" ON public.cash_outflow_concepts;
CREATE POLICY "cash_outflow_concepts_all"
  ON public.cash_outflow_concepts FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ============================================================
-- Realtime (opcional): para que el dispositivo que NO registra
-- el cambio lo reciba sin recargar. Mismo patrón que billiard_tables.
-- Si no lo quieres en tiempo real, puedes omitir este bloque.
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'cash_outflow_concepts'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.cash_outflow_concepts;
  END IF;
END $$;
