-- ============================================================
-- RECUPERACION COMPLETA SUPABASE - Baumar POS
-- Ejecutar en Supabase SQL Editor (New Query)
-- ============================================================

create extension if not exists "uuid-ossp";

-- ============================================================
-- FUNCION UTILITARIA
-- ============================================================
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- ============================================================
-- 1. BILLAR_SETTINGS
-- ============================================================
create table if not exists public.billar_settings (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    billar_id text not null default 'BILLAR_001',
    business_name text not null default 'Baumar Billar',
    table_count int not null default 8,
    hourly_rate double precision not null default 0.0,
    primary_color integer default 4293789907,
    business_address text default '',
    business_street text default '',
    business_ext_number text default '',
    business_int_number text default '',
    business_colony text default '',
    business_zip_code text default '',
    business_city text default '',
    business_state text default '',
    business_phone text default '',
    business_whatsapp text default '',
    business_slogan text default '',
    business_website text default '',
    ticket_farewell text default 'GRACIAS POR SU COMPRA',
    ticket_counter integer default 0,
    social_networks text default '{}',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.billar_settings enable row level security;

drop policy if exists "billar_settings_select" on public.billar_settings;
drop policy if exists "billar_settings_insert" on public.billar_settings;
drop policy if exists "billar_settings_update" on public.billar_settings;
drop policy if exists "billar_settings_delete" on public.billar_settings;

create policy "billar_settings_select" on public.billar_settings for select to authenticated using (user_id = auth.uid());
create policy "billar_settings_insert" on public.billar_settings for insert to authenticated with check (user_id = auth.uid());
create policy "billar_settings_update" on public.billar_settings for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "billar_settings_delete" on public.billar_settings for delete to authenticated using (user_id = auth.uid());

create unique index if not exists idx_billar_settings_user on public.billar_settings (user_id);

drop trigger if exists billar_settings_updated_at on public.billar_settings;
create trigger billar_settings_updated_at before update on public.billar_settings
    for each row execute function public.set_updated_at();

-- ============================================================
-- 2. PROVIDERS
-- ============================================================
create table if not exists public.providers (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text default '',
    email text default '',
    address text default '',
    contact_name text default '',
    notes text default '',
    category text default 'General',
    visit_days text default '',
    billar_id text not null default 'BILLAR_001',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.providers enable row level security;

drop policy if exists "providers_select" on public.providers;
drop policy if exists "providers_insert" on public.providers;
drop policy if exists "providers_update" on public.providers;
drop policy if exists "providers_delete" on public.providers;

create policy "providers_select" on public.providers for select to authenticated using (true);
create policy "providers_insert" on public.providers for insert to authenticated with check (true);
create policy "providers_update" on public.providers for update to authenticated using (true) with check (true);
create policy "providers_delete" on public.providers for delete to authenticated using (true);

create index if not exists idx_providers_billar on public.providers (billar_id);

drop trigger if exists providers_updated_at on public.providers;
create trigger providers_updated_at before update on public.providers
    for each row execute function public.set_updated_at();

-- ============================================================
-- 3. PRODUCTS
-- ============================================================
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    billar_id text not null default 'BILLAR_001',
    barcode text,
    name text not null,
    description text default '',
    price double precision not null default 0.0,
    cost double precision not null default 0.0,
    stock double precision not null default 0.0,
    image_path text,
    is_promo integer not null default 0,
    parent_id bigint,
    pieces_per_unit integer not null default 1,
    category text default '',
    presentation text default '',
    synced integer not null default 0,
    cloud_id text,
    created_at timestamptz default now()
);

alter table public.products enable row level security;

drop policy if exists "products_select" on public.products;
drop policy if exists "products_insert" on public.products;
drop policy if exists "products_update" on public.products;
drop policy if exists "products_delete" on public.products;

create policy "products_select" on public.products for select to authenticated using (true);
create policy "products_insert" on public.products for insert to authenticated with check (true);
create policy "products_update" on public.products for update to authenticated using (true) with check (true);
create policy "products_delete" on public.products for delete to authenticated using (true);

create index if not exists idx_products_billar on public.products (billar_id);
create index if not exists idx_products_barcode on public.products (barcode);

-- ============================================================
-- 4. CATEGORIES
-- ============================================================
create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    billar_id text not null default 'BILLAR_001',
    name text not null,
    constraint categories_name_unique unique (name)
);

alter table public.categories enable row level security;

drop policy if exists "categories_all" on public.categories;
create policy "categories_all" on public.categories for all to authenticated using (true) with check (true);

-- ============================================================
-- 5. PROMO_ITEMS
-- ============================================================
create table if not exists public.promo_items (
    id bigint generated by default as identity primary key,
    parent_id bigint not null references public.products(id) on delete cascade,
    child_id bigint not null,
    quantity integer not null default 1
);

alter table public.promo_items enable row level security;

drop policy if exists "promo_items_select" on public.promo_items;
drop policy if exists "promo_items_insert" on public.promo_items;
drop policy if exists "promo_items_delete" on public.promo_items;

create policy "promo_items_select" on public.promo_items for select to authenticated using (true);
create policy "promo_items_insert" on public.promo_items for insert to authenticated with check (true);
create policy "promo_items_delete" on public.promo_items for delete to authenticated using (true);

create index if not exists idx_promo_items_parent on public.promo_items (parent_id);

-- ============================================================
-- 6. PROVIDER_PRODUCTS
-- ============================================================
create table if not exists public.provider_products (
    id bigint generated by default as identity primary key,
    provider_id bigint not null references public.providers(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    created_at timestamptz default now(),
    unique (provider_id, product_id)
);

alter table public.provider_products enable row level security;

drop policy if exists "provider_products_select" on public.provider_products;
drop policy if exists "provider_products_insert" on public.provider_products;
drop policy if exists "provider_products_delete" on public.provider_products;

create policy "provider_products_select" on public.provider_products for select to authenticated using (true);
create policy "provider_products_insert" on public.provider_products for insert to authenticated with check (true);
create policy "provider_products_delete" on public.provider_products for delete to authenticated using (true);

create index if not exists idx_provider_products_provider on public.provider_products (provider_id);
create index if not exists idx_provider_products_product on public.provider_products (product_id);

-- ============================================================
-- 7. BILLIARD_TABLES
-- ============================================================
create table if not exists public.billiard_tables (
    id bigint not null,
    billar_id text not null default 'BILLAR_001',
    name text not null default 'Mesa',
    table_type text not null default 'Billar',
    is_occupied int not null default 0,
    start_time timestamptz,
    orders text default '[]',
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    primary key (billar_id, id)
);

alter table public.billiard_tables enable row level security;

drop policy if exists "billiard_tables_select" on public.billiard_tables;
drop policy if exists "billiard_tables_insert" on public.billiard_tables;
drop policy if exists "billiard_tables_update" on public.billiard_tables;
drop policy if exists "billiard_tables_delete" on public.billiard_tables;

create policy "billiard_tables_select" on public.billiard_tables for select to authenticated using (true);
create policy "billiard_tables_insert" on public.billiard_tables for insert to authenticated with check (true);
create policy "billiard_tables_update" on public.billiard_tables for update to authenticated using (true) with check (true);
create policy "billiard_tables_delete" on public.billiard_tables for delete to authenticated using (true);

create index if not exists idx_billiard_tables_billar on public.billiard_tables (billar_id);

drop trigger if exists billiard_tables_updated_at on public.billiard_tables;
create trigger billiard_tables_updated_at before update on public.billiard_tables
    for each row execute function public.set_updated_at();

-- ============================================================
-- 8. SALES_HISTORY
-- ============================================================
create table if not exists public.sales_history (
    id bigint generated by default as identity primary key,
    billar_id text not null default 'BILLAR_001',
    total double precision not null,
    paid double precision not null default 0,
    date text not null,
    type text not null,
    payment_method text not null default 'Efectivo',
    synced integer not null default 0,
    cloud_id text,
    created_at timestamptz default now()
);

alter table public.sales_history enable row level security;

drop policy if exists "sales_select" on public.sales_history;
drop policy if exists "sales_insert" on public.sales_history;
drop policy if exists "sales_update" on public.sales_history;
drop policy if exists "sales_delete" on public.sales_history;

create policy "sales_select" on public.sales_history for select to authenticated using (true);
create policy "sales_insert" on public.sales_history for insert to authenticated with check (true);
create policy "sales_update" on public.sales_history for update to authenticated using (true) with check (true);
create policy "sales_delete" on public.sales_history for delete to authenticated using (true);

create index if not exists idx_sales_billar on public.sales_history (billar_id);
create index if not exists idx_sales_date on public.sales_history (date desc);

-- ============================================================
-- 9. SALE_DETAILS
-- ============================================================
create table if not exists public.sale_details (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references public.sales_history(id) on delete cascade,
    product_id bigint,
    product_name text not null,
    quantity double precision not null,
    price_at_sale double precision not null
);

alter table public.sale_details enable row level security;

drop policy if exists "sale_details_select" on public.sale_details;
drop policy if exists "sale_details_insert" on public.sale_details;
drop policy if exists "sale_details_delete" on public.sale_details;

create policy "sale_details_select" on public.sale_details for select to authenticated using (true);
create policy "sale_details_insert" on public.sale_details for insert to authenticated with check (true);
create policy "sale_details_delete" on public.sale_details for delete to authenticated using (true);

create index if not exists idx_sale_details_sale on public.sale_details (sale_id);

-- ============================================================
-- 10. PURCHASES
-- ============================================================
create table if not exists public.purchases (
    id bigint generated by default as identity primary key,
    provider_id bigint references public.providers(id),
    total double precision not null,
    date text not null,
    reference text default '',
    billar_id text not null default 'BILLAR_001',
    synced integer not null default 0,
    cloud_id text,
    created_at timestamptz default now()
);

alter table public.purchases enable row level security;

drop policy if exists "purchases_select" on public.purchases;
drop policy if exists "purchases_insert" on public.purchases;
drop policy if exists "purchases_update" on public.purchases;
drop policy if exists "purchases_delete" on public.purchases;

create policy "purchases_select" on public.purchases for select to authenticated using (true);
create policy "purchases_insert" on public.purchases for insert to authenticated with check (true);
create policy "purchases_update" on public.purchases for update to authenticated using (true) with check (true);
create policy "purchases_delete" on public.purchases for delete to authenticated using (true);

create index if not exists idx_purchases_billar on public.purchases (billar_id);
create index if not exists idx_purchases_date on public.purchases (date desc);

-- ============================================================
-- 11. PURCHASE_DETAILS
-- ============================================================
create table if not exists public.purchase_details (
    id bigint generated by default as identity primary key,
    purchase_id bigint not null references public.purchases(id) on delete cascade,
    product_id bigint not null,
    quantity double precision not null,
    cost_per_unit double precision not null
);

alter table public.purchase_details enable row level security;

drop policy if exists "purchase_details_select" on public.purchase_details;
drop policy if exists "purchase_details_insert" on public.purchase_details;
drop policy if exists "purchase_details_delete" on public.purchase_details;

create policy "purchase_details_select" on public.purchase_details for select to authenticated using (true);
create policy "purchase_details_insert" on public.purchase_details for insert to authenticated with check (true);
create policy "purchase_details_delete" on public.purchase_details for delete to authenticated using (true);

create index if not exists idx_purchase_details_purchase on public.purchase_details (purchase_id);

-- ============================================================
-- 12. PENDING_SALES
-- ============================================================
create table if not exists public.pending_sales (
    id uuid default uuid_generate_v4() primary key,
    billar_id text not null default 'BILLAR_001',
    product text not null,
    quantity int not null,
    price double precision not null,
    created_at timestamptz default now()
);

alter table public.pending_sales enable row level security;

drop policy if exists "pending_sales_select" on public.pending_sales;
drop policy if exists "pending_sales_insert" on public.pending_sales;

create policy "pending_sales_select" on public.pending_sales for select to authenticated using (true);
create policy "pending_sales_insert" on public.pending_sales for insert to authenticated with check (true);

create index if not exists idx_pending_sales_billar on public.pending_sales (billar_id);

-- ============================================================
-- 13. PLAYERS
-- ============================================================
create table if not exists public.players (
    id uuid default uuid_generate_v4() primary key,
    name text not null,
    nickname text default '',
    avatar text default '',
    wins integer not null default 0,
    losses integer not null default 0,
    draws integer not null default 0,
    total_matches integer not null default 0,
    total_seconds integer not null default 0,
    break_and_run integer not null default 0,
    golden_breaks integer not null default 0,
    high_run integer not null default 0,
    current_streak integer not null default 0,
    best_streak integer not null default 0,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    local_id integer,
    billar_id text default 'BILLAR_001',
    cloud_id text
);

alter table public.players enable row level security;

drop policy if exists "players_select" on public.players;
drop policy if exists "players_insert" on public.players;
drop policy if exists "players_update" on public.players;
drop policy if exists "players_delete" on public.players;

create policy "players_select" on public.players for select to authenticated using (true);
create policy "players_insert" on public.players for insert to authenticated with check (true);
create policy "players_update" on public.players for update to authenticated using (true) with check (true);
create policy "players_delete" on public.players for delete to authenticated using (true);

create index if not exists idx_players_billar on public.players (billar_id);
create index if not exists idx_players_local_id on public.players (local_id);

drop trigger if exists players_updated_at on public.players;
create trigger players_updated_at before update on public.players
    for each row execute function public.set_updated_at();

-- ============================================================
-- 14. MATCH_RESULTS
-- ============================================================
create table if not exists public.match_results (
    id uuid default uuid_generate_v4() primary key,
    game_type text not null default 'Bola 8',
    player1_id uuid references public.players(id) on delete cascade,
    player2_id uuid references public.players(id) on delete cascade,
    winner_id uuid references public.players(id) on delete set null,
    player_score integer not null default 0,
    opponent_score integer not null default 0,
    accuracy double precision not null default 0,
    efficiency double precision not null default 0,
    is_draw boolean not null default false,
    golden_break boolean not null default false,
    break_and_run boolean not null default false,
    notes text default '',
    match_date timestamptz default now(),
    created_at timestamptz default now(),
    local_id integer,
    billar_id text default 'BILLAR_001'
);

alter table public.match_results enable row level security;

drop policy if exists "match_select" on public.match_results;
drop policy if exists "match_insert" on public.match_results;
drop policy if exists "match_update" on public.match_results;
drop policy if exists "match_delete" on public.match_results;

create policy "match_select" on public.match_results for select to authenticated using (true);
create policy "match_insert" on public.match_results for insert to authenticated with check (true);
create policy "match_update" on public.match_results for update to authenticated using (true) with check (true);
create policy "match_delete" on public.match_results for delete to authenticated using (true);

create index if not exists idx_matches_billar on public.match_results (billar_id);
create index if not exists idx_matches_date on public.match_results (match_date desc);
create index if not exists idx_matches_players on public.match_results (player1_id, player2_id);
create index if not exists idx_matches_winner on public.match_results (winner_id);

-- ============================================================
-- 15. STORAGE BUCKETS
-- ============================================================
insert into storage.buckets (id, name, public)
values
  ('product_images', 'product_images', true),
  ('promo_images', 'promo_images', true),
  ('player_avatars', 'player_avatars', true)
on conflict (id) do nothing;

drop policy if exists "product_images_select" on storage.objects;
create policy "product_images_select" on storage.objects for select using (bucket_id = 'product_images');

drop policy if exists "product_images_insert" on storage.objects;
create policy "product_images_insert" on storage.objects for insert with check (bucket_id = 'product_images' and auth.role() = 'authenticated');

drop policy if exists "product_images_update" on storage.objects;
create policy "product_images_update" on storage.objects for update using (bucket_id = 'product_images' and auth.role() = 'authenticated');

drop policy if exists "product_images_delete" on storage.objects;
create policy "product_images_delete" on storage.objects for delete using (bucket_id = 'product_images' and auth.role() = 'authenticated');

drop policy if exists "promo_images_select" on storage.objects;
create policy "promo_images_select" on storage.objects for select using (bucket_id = 'promo_images');

drop policy if exists "promo_images_insert" on storage.objects;
create policy "promo_images_insert" on storage.objects for insert with check (bucket_id = 'promo_images' and auth.role() = 'authenticated');

drop policy if exists "promo_images_update" on storage.objects;
create policy "promo_images_update" on storage.objects for update using (bucket_id = 'promo_images' and auth.role() = 'authenticated');

drop policy if exists "promo_images_delete" on storage.objects;
create policy "promo_images_delete" on storage.objects for delete using (bucket_id = 'promo_images' and auth.role() = 'authenticated');

drop policy if exists "player_avatars_select" on storage.objects;
create policy "player_avatars_select" on storage.objects for select using (bucket_id = 'player_avatars');

drop policy if exists "player_avatars_insert" on storage.objects;
create policy "player_avatars_insert" on storage.objects for insert with check (bucket_id = 'player_avatars' and auth.role() = 'authenticated');

drop policy if exists "player_avatars_update" on storage.objects;
create policy "player_avatars_update" on storage.objects for update using (bucket_id = 'player_avatars' and auth.role() = 'authenticated');

drop policy if exists "player_avatars_delete" on storage.objects;
create policy "player_avatars_delete" on storage.objects for delete using (bucket_id = 'player_avatars' and auth.role() = 'authenticated');

-- ============================================================
-- VERIFICACION RAPIDA
-- ============================================================
select table_name from information_schema.tables where table_schema = 'public' order by table_name;
