-- ============================================================
-- SCHEMA SUPABASE - Baumar POS (ESTADO REAL)
-- Copiar y pegar en Supabase SQL Editor para crear TODO desde cero
-- O usar migrate_supabase.sql para migrar tablas existentes
-- ============================================================

create extension if not exists "uuid-ossp";

-- ============================================================
-- FUNCION UTILITARIA: updated_at automatico
-- ============================================================
create or replace function public.set_updated_at()
    returns trigger as $$
    begin
        new.updated_at = now();
        return new;
    end;
    $$ language plpgsql;

-- ============================================================
-- TABLA: providers
-- ============================================================
create table if not exists public.providers (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text default '',
    address text default '',
    category text default 'Lunes',
    created_at timestamptz default now()
);

alter table public.providers enable row level security;

create policy "providers_select" on public.providers for
select to authenticated using (true);

create policy "providers_insert" on public.providers for
insert
    to authenticated
with
    check (true);

create policy "providers_update" on public.providers for
update to authenticated using (true)
with
    check (true);

create policy "providers_delete" on public.providers for delete to authenticated using (true);

-- ============================================================
-- TABLA: products
-- ============================================================
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    billar_id text not null default 'BILLAR_001',
    barcode text,
    name text not null,
    description text default '',
    price numeric not null default 0.0,
    cost numeric not null default 0.0,
    stock numeric not null default 0.0,
    image_path text,
    is_promo integer not null default 0,
    parent_id bigint,
    pieces_per_unit integer not null default 1,
    created_at timestamptz default now()
);

alter table public.products enable row level security;

create policy "products_select" on public.products for
select to authenticated using (true);

create policy "products_insert" on public.products for
insert
    to authenticated
with
    check (true);

create policy "products_update" on public.products for
update to authenticated using (true)
with
    check (true);

create policy "products_delete" on public.products for delete to authenticated using (true);

create index idx_products_billar on public.products (billar_id);

create index idx_products_barcode on public.products (barcode);

-- ============================================================
-- TABLA: promo_items
-- ============================================================
create table if not exists public.promo_items (
    id bigint generated by default as identity primary key,
    parent_id bigint not null references public.products (id) on delete cascade,
    child_id bigint not null,
    quantity integer not null
);

alter table public.promo_items enable row level security;

create policy "promo_items_select" on public.promo_items for
select to authenticated using (true);

create policy "promo_items_insert" on public.promo_items for
insert
    to authenticated
with
    check (true);

create policy "promo_items_delete" on public.promo_items for delete to authenticated using (true);

create index idx_promo_items_parent on public.promo_items (parent_id);

-- ============================================================
-- TABLA: billiard_tables (solo local, no necesita Supabase)
-- ============================================================
-- NO se crea en Supabase. Se mantiene solo en SQLite.

-- ============================================================
-- TABLA: sales_history
-- ============================================================
create table if not exists public.sales_history (
    id bigint generated by default as identity primary key,
    billar_id text not null default 'BILLAR_001',
    total numeric not null,
    paid numeric not null default 0,
    date text not null,
    type text not null,
    payment_method text not null default 'Efectivo',
    created_at timestamptz default now()
);

alter table public.sales_history enable row level security;

create policy "sales_select" on public.sales_history for
select to authenticated using (true);

create policy "sales_insert" on public.sales_history for
insert
    to authenticated
with
    check (true);

create policy "sales_update" on public.sales_history for
update to authenticated using (true)
with
    check (true);

create policy "sales_delete" on public.sales_history for delete to authenticated using (true);

create index idx_sales_billar on public.sales_history (billar_id);

create index idx_sales_date on public.sales_history (date desc);

-- ============================================================
-- TABLA: sale_details
-- ============================================================
create table if not exists public.sale_details (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references public.sales_history (id) on delete cascade,
    product_id bigint,
    product_name text not null,
    quantity numeric not null,
    price_at_sale numeric not null
);

alter table public.sale_details enable row level security;

create policy "sale_details_select" on public.sale_details for
select to authenticated using (true);

create policy "sale_details_insert" on public.sale_details for
insert
    to authenticated
with
    check (true);

create policy "sale_details_delete" on public.sale_details for delete to authenticated using (true);

create index idx_sale_details_sale on public.sale_details (sale_id);

-- ============================================================
-- TABLA: purchases
-- ============================================================
create table if not exists public.purchases (
    id bigint generated by default as identity primary key,
    provider_id bigint references public.providers (id),
    total numeric not null,
    date text not null,
    reference text default '',
    billar_id text not null default 'BILLAR_001',
    synced integer not null default 0,
    cloud_id text,
    created_at timestamptz default now()
);

alter table public.purchases enable row level security;

create policy "purchases_select" on public.purchases for
select to authenticated using (true);

create policy "purchases_insert" on public.purchases for
insert
    to authenticated
with
    check (true);

create policy "purchases_update" on public.purchases for
update to authenticated using (true)
with
    check (true);

create policy "purchases_delete" on public.purchases for delete to authenticated using (true);

create index idx_purchases_billar on public.purchases (billar_id);

create index idx_purchases_date on public.purchases (date desc);

-- ============================================================
-- TABLA: purchase_details
-- ============================================================
create table if not exists public.purchase_details (
    id bigint generated by default as identity primary key,
    purchase_id bigint not null references public.purchases (id) on delete cascade,
    product_id bigint not null,
    quantity numeric not null,
    cost_per_unit numeric not null
);

alter table public.purchase_details enable row level security;

create policy "purchase_details_select" on public.purchase_details for
select to authenticated using (true);

create policy "purchase_details_insert" on public.purchase_details for
insert
    to authenticated
with
    check (true);

create policy "purchase_details_delete" on public.purchase_details for delete to authenticated using (true);

create index idx_purchase_details_purchase on public.purchase_details (purchase_id);

-- ============================================================
-- TABLA: pending_sales
-- ============================================================
create table if not exists public.pending_sales (
    id uuid default uuid_generate_v4 () primary key,
    billar_id text not null default 'BILLAR_001',
    product text not null,
    quantity integer not null,
    price numeric not null,
    created_at timestamptz default now()
);

alter table public.pending_sales enable row level security;

create policy "pending_sales_select" on public.pending_sales for
select to authenticated using (true);

create policy "pending_sales_insert" on public.pending_sales for
insert
    to authenticated
with
    check (true);

create index idx_pending_sales_billar on public.pending_sales (billar_id);

-- ============================================================
-- TABLA: players
-- ============================================================
create table if not exists public.players (
    id uuid default uuid_generate_v4 () primary key,
    name text not null,
    nickname text default '',
    avatar_url text default '',
    handicap integer not null default 0,
    wins integer not null default 0,
    losses integer not null default 0,
    draws integer not null default 0,
    total_matches integer not null default 0,
    total_seconds integer not null default 0,
    break_and_run integer not null default 0,
    golden_breaks integer not null default 0,
    high_run integer not null default 0,
    current_streak integer not null default 0,
    best_streak integer not null default 0,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    local_id integer,
    billar_id text default 'BILLAR_001',
    version integer default 1
);

alter table public.players enable row level security;

create policy "players_select" on public.players for
select to authenticated using (true);

create policy "players_insert" on public.players for
insert
    to authenticated
with
    check (true);

create policy "players_update" on public.players for
update to authenticated using (true)
with
    check (true);

create policy "players_delete" on public.players for delete to authenticated using (true);

create index idx_players_billar on public.players (billar_id);

create index idx_players_local_id on public.players (local_id);

drop trigger if exists players_updated_at on public.players;

create trigger players_updated_at before update on public.players
        for each row execute function public.set_updated_at();

-- ============================================================
-- TABLA: match_results
-- ============================================================
create table if not exists public.match_results (
    id uuid default uuid_generate_v4 () primary key,
    game_type text not null default 'Bola 8',
    player1_id uuid not null references public.players (id) on delete cascade,
    player2_id uuid not null references public.players (id) on delete cascade,
    winner_id uuid references public.players (id) on delete set null,
    is_draw boolean not null default false,
    golden_break boolean not null default false,
    break_and_run boolean not null default false,
    notes text default '',
    match_date timestamptz default now(),
    created_at timestamptz default now(),
    local_id integer,
    billar_id text default 'BILLAR_001'
);

alter table public.match_results enable row level security;

create policy "match_select" on public.match_results for
select to authenticated using (true);

create policy "match_insert" on public.match_results for
insert
    to authenticated
with
    check (true);

create policy "match_update" on public.match_results for
update to authenticated using (true)
with
    check (true);

create policy "match_delete" on public.match_results for delete to authenticated using (true);

create index idx_matches_billar on public.match_results (billar_id);

create index idx_matches_date on public.match_results (match_date desc);

create index idx_matches_players on public.match_results (player1_id, player2_id);

create index idx_matches_winner on public.match_results (winner_id);

-- ============================================================
-- TABLA: billar_settings
-- ============================================================
create table if not exists public.billar_settings (
    id uuid default uuid_generate_v4 () primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    billar_id text not null default 'BILLAR_001',
    business_name text not null default 'Baumar Billar',
    table_count integer not null default 8,
    hourly_rate double precision not null default 0.0,
    primary_color integer default 0xFFE53935,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.billar_settings enable row level security;

create policy "billar_settings_select" on public.billar_settings for
select to authenticated using (user_id = auth.uid ());

create policy "billar_settings_insert" on public.billar_settings for
insert
    to authenticated
with
    check (user_id = auth.uid ());

create policy "billar_settings_update" on public.billar_settings for
update to authenticated using (user_id = auth.uid ())
with
    check (user_id = auth.uid ());

create policy "billar_settings_delete" on public.billar_settings for delete to authenticated using (user_id = auth.uid ());

create unique index idx_billar_settings_user on public.billar_settings (user_id);

drop trigger if exists billar_settings_updated_at on public.billar_settings;

create trigger billar_settings_updated_at before update on public.billar_settings
        for each row execute function public.set_updated_at();

-- ============================================================
-- TABLA sales VIEJA:
-- Si existe y no tiene datos utiles, eliminarla con:
--   DROP TABLE public.sales CASCADE;
-- Esta tabla no es usada por la app actual.
-- ============================================================