name: app_integral_complete
description: "App Integral POS - Billar, Ventas, Inventario, Compras"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  supabase_flutter: ^2.12.2
  app_links: ^7.2.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  sqlite3_flutter_libs: ^0.6.0+eol
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.3.1
  image_picker: ^1.2.1
  file_picker: ^8.0.5
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^12.0.2
  blue_thermal_printer: ^1.1.1
  mobile_scanner: ^7.0.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/baumar_8_personal-sf.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/baumar_8_personal-sf.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/baumar_8_personal-sf.png
    - assets/balls/
    - .env
